spring.application.name=Todo
server.port=8083

# MongoDB Secure Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/Todo}
spring.data.mongodb.database=Todo
spring.data.mongodb.auto-index-creation=true

# Email Secure Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:taskzen4@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:fdkijqwdlozgxdps}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Secure Configuration
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey123}

# Logging Configuration
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR