spring.application.name=Todo
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}


spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=taskzen_db
spring.data.mongodb.auto-index-creation=true

# Security & Mail (Adding the missing spring. prefixes)
spring.security.jwt.secret=${JWT_SECRET}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true